
language: cpp

matrix:
    include:
        - os: osx
          osx_image: xcode8
          compiler:
              - clang
          before_install:
              - ./ci/install_deps_osx.sh
          cache:
              directories:
                  - $HOME/Library/Caches/Homebrew
          script: 
              - ./ci/clang-format.sh
              - tools/build.py

        - os: linux
          sudo: required
          services:
              - docker
          dist: trusty
          before_install:
              - docker build -t mengde docker
          script:
              # clang format is disabled for ubuntu due to version issue
#              - ./ci/clang-format.sh
              - docker run --rm -it -v $(pwd):/root/mengde -w /root/mengde mengde tools/build.py
